# Generated by Django 6.0.4 on 2026-05-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesanAnonim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_pesan', models.TextField()),
                ('ip_pengirim', models.GenericIPAddressField(blank=True, null=True)),
                ('perangkat_pengirim', models.CharField(blank=True, max_length=255, null=True)),
                ('asal_link', models.CharField(default='Langsung/Ketik Sendiri', max_length=100)),
                ('nama_pelacak', models.CharField(default='Anonim', max_length=100)),
                ('waktu_dikirim', models.DateTimeField(auto_now_add=True)),
                ('dibuka', models.BooleanField(default=False)),
            ],
        ),
    ]
